/**
 * Language Context - Multilingual support for Tru & Co
 * Supports: English (US), Spanish (ES), Portuguese (BR), French (FR), Italian (IT)
 */

import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "en" | "es" | "pt" | "fr" | "it";

export interface LanguageInfo {
  code: Language;
  label: string;
  flag: string; // emoji flag
  nativeName: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", label: "English", flag: "🇺🇸", nativeName: "English" },
  { code: "es", label: "Spanish", flag: "🇪🇸", nativeName: "Español" },
  { code: "pt", label: "Portuguese", flag: "🇧🇷", nativeName: "Português" },
  { code: "fr", label: "French", flag: "🇫🇷", nativeName: "Français" },
  { code: "it", label: "Italian", flag: "🇮🇹", nativeName: "Italiano" },
];

type TranslationDict = Record<string, string>;
type Translations = Record<Language, TranslationDict>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// ============================================================
// TRANSLATIONS
// ============================================================

const translations: Translations = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.about": "About",
    "nav.peptides": "World of Peptides",
    "nav.contact": "Contact us",
    "nav.prc": "PRC - Peptide Reconstitution Calculator",

    // Hero / Home
    "home.typewriter": "Lab-Tested Peptides At An Affordable Price",
    "home.badge1": "ISO 9001 Certified",
    "home.badge2": "99%+ Satisfaction",
    "home.badge3": "Global Distribution",
    "home.headline": "Global Health.",
    "home.headline2": "True",
    "home.headline3": "Solutions.",
    "home.subheadline": "Trusted source for pharmaceutical-grade research products. Third party tested, pre-mixed, and ready for laboratory use.",
    "home.exploreBtn": "Explore Our Peptides",
    "home.contactBtn": "Contact Us",
    "home.statsTitle": "Trusted by Researchers Worldwide",
    "home.statsSubtitle": "Our commitment to quality and innovation has earned the trust of research institutions globally.",
    "home.stat1.value": "99%+",
    "home.stat1.label": "Purity Rate",
    "home.stat1.desc": "Verified by independent third-party laboratories",
    "home.stat2.value": "50+",
    "home.stat2.label": "Countries Served",
    "home.stat2.desc": "Global distribution network with reliable shipping",
    "home.stat3.value": "500+",
    "home.stat3.label": "Research Products",
    "home.stat3.desc": "Comprehensive catalog of peptides and compounds",
    "home.stat4.value": "24/7",
    "home.stat4.label": "Support Available",
    "home.stat4.desc": "Dedicated team for technical and order assistance",
    "home.whyTitle": "Why Choose Tru & Co?",
    "home.whySubtitle": "We combine scientific rigor with accessible pricing to support researchers worldwide.",
    "home.why1.title": "Lab-Tested Purity",
    "home.why1.desc": "Every batch undergoes rigorous third-party testing to ensure 99%+ purity for reliable research outcomes.",
    "home.why2.title": "Affordable Pricing",
    "home.why2.desc": "Premium quality peptides at competitive prices, making advanced research accessible to all laboratories.",
    "home.why3.title": "Global Shipping",
    "home.why3.desc": "Fast, secure worldwide delivery with proper cold-chain handling to maintain product integrity.",
    "home.why4.title": "Expert Support",
    "home.why4.desc": "Our team of specialists provides technical guidance and responsive customer service.",
    "home.why5.title": "GMP Standards",
    "home.why5.desc": "Manufactured following Good Manufacturing Practice guidelines for consistent quality.",
    "home.why6.title": "Extensive Catalog",
    "home.why6.desc": "Over 500 research compounds including peptides, proteins, and small molecules.",
    "home.ctaTitle": "Ready to Advance Your Research?",
    "home.ctaSubtitle": "Join thousands of researchers worldwide who trust Tru & Co for their peptide needs.",
    "home.ctaBtn": "Get Started Today",
    "home.ctaContact": "Contact Our Team",

    // About
    "about.title": "About Tru & Co",
    "about.subtitle": "Pioneering accessible research solutions with pharmaceutical-grade quality.",
    "about.missionTitle": "Our Mission",
    "about.missionText": "At Tru & Co, we believe that groundbreaking research shouldn't be limited by budget constraints. Our mission is to provide the global scientific community with lab-tested, pharmaceutical-grade peptides at prices that make advanced research accessible to all.",
    "about.visionTitle": "Our Vision",
    "about.visionText": "To become the world's most trusted supplier of research peptides, setting new standards for quality, affordability, and scientific integrity in the research supply industry.",
    "about.valuesTitle": "Our Core Values",
    "about.value1.title": "Scientific Integrity",
    "about.value1.desc": "Every product undergoes rigorous testing and quality control to ensure the highest standards of purity and reliability.",
    "about.value2.title": "Accessibility",
    "about.value2.desc": "We believe quality research materials should be available to laboratories of all sizes, not just well-funded institutions.",
    "about.value3.title": "Innovation",
    "about.value3.desc": "Continuously expanding our catalog and improving our processes to meet the evolving needs of the research community.",
    "about.value4.title": "Transparency",
    "about.value4.desc": "Open communication about our testing methods, sourcing, and quality standards builds trust with our customers.",
    "about.teamTitle": "Leadership & Expertise",
    "about.teamSubtitle": "Our team combines decades of experience in pharmaceutical research, quality assurance, and global logistics.",
    "about.certTitle": "Quality Certifications",
    "about.certSubtitle": "Our commitment to quality is backed by internationally recognized certifications.",

    // Peptides
    "peptides.title": "World of Peptides",
    "peptides.subtitle": "Selected Peptides & Research Context",
    "peptides.searchPlaceholder": "Search compounds...",
    "peptides.showing": "Showing",
    "peptides.of": "of",
    "peptides.compounds": "compounds",
    "peptides.noResults": "No compounds found matching your search.",
    "peptides.clearFilters": "Clear filters",
    "peptides.reference": "Reference:",
    "peptides.references": "References:",
    "peptides.all": "All",

    // Calculator
    "calc.title": "PRC - Peptide Reconstitution Calculator",
    "calc.subtitle": "Calculate precise reconstitution volumes and dosing for your research peptides.",
    "calc.breadcrumbHome": "Home",
    "calc.selectPeptide": "Select Peptide",
    "calc.searchPeptide": "Search peptide...",
    "calc.vialSize": "Vial Size (mg)",
    "calc.bacWater": "BAC Water (mL)",
    "calc.desiredDose": "Desired Dose (mcg)",
    "calc.calculate": "Calculate",
    "calc.reset": "Reset",
    "calc.results": "Results",
    "calc.concentration": "Concentration",
    "calc.volumePerDose": "Volume per Dose",
    "calc.syringeUnits": "Syringe Units (U-100)",
    "calc.dosesPerVial": "Doses per Vial",
    "calc.howItWorks": "How It Works",
    "calc.step1.title": "Select Your Peptide",
    "calc.step1.desc": "Choose from our database of 100+ research peptides. Vial sizes auto-populate.",
    "calc.step2.title": "Set BAC Water Volume",
    "calc.step2.desc": "Select how much bacteriostatic water you'll use for reconstitution.",
    "calc.step3.title": "Enter Desired Dose",
    "calc.step3.desc": "Input your target dose in micrograms (mcg) for precise calculations.",
    "calc.step4.title": "Get Your Results",
    "calc.step4.desc": "Receive concentration, volume per dose, syringe units, and doses per vial.",
    "calc.peptideVial": "Peptide Vial",
    "calc.lyophilized": "Lyophilized powder",
    "calc.u100Syringe": "U-100 Syringe",
    "calc.u100Desc": "1mL = 100 units",
    "calc.keyFormulas": "Key Formulas",
    "calc.faqTitle": "Frequently Asked Questions",
    "calc.disclaimer": "This calculator is for research reference only. Always verify calculations independently. Not for human use.",

    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions about our products or need assistance? We're here to help.",
    "contact.formTitle": "Send us a Message",
    "contact.name": "Full Name",
    "contact.email": "Email Address",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.success": "Message sent successfully!",
    "contact.error": "Failed to send message. Please try again.",
    "contact.infoTitle": "Get in Touch",
    "contact.emailLabel": "Email",
    "contact.locationLabel": "Location",
    "contact.hoursLabel": "Business Hours",
    "contact.hoursValue": "Monday - Friday, 9:00 AM - 6:00 PM EST",
    "contact.responseLabel": "Response Time",
    "contact.responseValue": "Within 24 hours",

    // Footer
    "footer.description": "Global Health. True Solutions. Transforming research through innovative and reliable peptide solutions.",
    "footer.quickLinks": "Quick Links",
    "footer.legal": "Legal",
    "footer.contactUs": "Contact us",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.researchOnly": "For Research Use Only",
    "footer.prc": "PRC - Reconstitution Calculator",
    "footer.rights": "All rights reserved.",
    "footer.termsShort": "Terms",
    "footer.privacyShort": "Privacy",
    "footer.disclaimer": "DISCLAIMER:",
    "footer.disclaimerText": "These products are not approved by the U.S. Food and Drug Administration (FDA) for human consumption or medical applications. They must not be used for any purpose other than scientific research. Statements presented on this website have not been evaluated by the U.S. Food and Drug Administration (FDA).",
    "footer.labResearch": "For laboratory research use only.",
    "footer.notForHuman": "Not for human or veterinary use consumption, or administration.",

    // GMP Badges
    "badge.gmp": "GMP Certified",
    "badge.iso": "ISO 9001 Certified",
    "badge.thirdParty": "3rd Party Tested",

    // Evidence Levels
    "evidence.all": "All Levels",
    "evidence.phaseIII": "Phase III / Approved",
    "evidence.phaseII": "Phase II",
    "evidence.clinical": "Clinical/Translational",
    "evidence.preclinical": "Preclinical",
    "evidence.mechanistic": "Mechanistic",

    // Terms
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last Updated",

    // Privacy
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last Updated",
  },

  es: {
    // Nav
    "nav.home": "Inicio",
    "nav.about": "Nosotros",
    "nav.peptides": "Mundo de los Péptidos",
    "nav.contact": "Contáctenos",
    "nav.prc": "PRC - Calculadora de Reconstitución",

    // Hero / Home
    "home.typewriter": "Péptidos Probados en Laboratorio a un Precio Accesible",
    "home.badge1": "Certificado ISO 9001",
    "home.badge2": "99%+ Satisfacción",
    "home.badge3": "Distribución Global",
    "home.headline": "Salud Global.",
    "home.headline2": "Verdaderas",
    "home.headline3": "Soluciones.",
    "home.subheadline": "Fuente confiable de productos de investigación de grado farmacéutico. Probados por terceros, premezclados y listos para uso en laboratorio.",
    "home.exploreBtn": "Explorar Nuestros Péptidos",
    "home.contactBtn": "Contáctenos",
    "home.statsTitle": "Confianza de Investigadores en Todo el Mundo",
    "home.statsSubtitle": "Nuestro compromiso con la calidad e innovación ha ganado la confianza de instituciones de investigación a nivel global.",
    "home.stat1.value": "99%+",
    "home.stat1.label": "Tasa de Pureza",
    "home.stat1.desc": "Verificado por laboratorios independientes de terceros",
    "home.stat2.value": "50+",
    "home.stat2.label": "Países Atendidos",
    "home.stat2.desc": "Red de distribución global con envío confiable",
    "home.stat3.value": "500+",
    "home.stat3.label": "Productos de Investigación",
    "home.stat3.desc": "Catálogo completo de péptidos y compuestos",
    "home.stat4.value": "24/7",
    "home.stat4.label": "Soporte Disponible",
    "home.stat4.desc": "Equipo dedicado para asistencia técnica y de pedidos",
    "home.whyTitle": "¿Por Qué Elegir Tru & Co?",
    "home.whySubtitle": "Combinamos rigor científico con precios accesibles para apoyar a investigadores en todo el mundo.",
    "home.why1.title": "Pureza Probada en Laboratorio",
    "home.why1.desc": "Cada lote se somete a pruebas rigurosas de terceros para garantizar una pureza del 99%+ para resultados de investigación confiables.",
    "home.why2.title": "Precios Accesibles",
    "home.why2.desc": "Péptidos de calidad premium a precios competitivos, haciendo la investigación avanzada accesible para todos los laboratorios.",
    "home.why3.title": "Envío Global",
    "home.why3.desc": "Entrega mundial rápida y segura con manejo adecuado de cadena de frío para mantener la integridad del producto.",
    "home.why4.title": "Soporte Experto",
    "home.why4.desc": "Nuestro equipo de especialistas proporciona orientación técnica y servicio al cliente receptivo.",
    "home.why5.title": "Estándares GMP",
    "home.why5.desc": "Fabricado siguiendo las directrices de Buenas Prácticas de Manufactura para una calidad consistente.",
    "home.why6.title": "Catálogo Extenso",
    "home.why6.desc": "Más de 500 compuestos de investigación incluyendo péptidos, proteínas y moléculas pequeñas.",
    "home.ctaTitle": "¿Listo para Avanzar en su Investigación?",
    "home.ctaSubtitle": "Únase a miles de investigadores en todo el mundo que confían en Tru & Co para sus necesidades de péptidos.",
    "home.ctaBtn": "Comience Hoy",
    "home.ctaContact": "Contacte a Nuestro Equipo",

    // About
    "about.title": "Sobre Tru & Co",
    "about.subtitle": "Pioneros en soluciones de investigación accesibles con calidad de grado farmacéutico.",
    "about.missionTitle": "Nuestra Misión",
    "about.missionText": "En Tru & Co, creemos que la investigación innovadora no debe estar limitada por restricciones presupuestarias. Nuestra misión es proporcionar a la comunidad científica global péptidos de grado farmacéutico probados en laboratorio a precios que hagan la investigación avanzada accesible para todos.",
    "about.visionTitle": "Nuestra Visión",
    "about.visionText": "Convertirnos en el proveedor más confiable del mundo de péptidos de investigación, estableciendo nuevos estándares de calidad, asequibilidad e integridad científica en la industria de suministros de investigación.",
    "about.valuesTitle": "Nuestros Valores Fundamentales",
    "about.value1.title": "Integridad Científica",
    "about.value1.desc": "Cada producto se somete a pruebas rigurosas y control de calidad para garantizar los más altos estándares de pureza y confiabilidad.",
    "about.value2.title": "Accesibilidad",
    "about.value2.desc": "Creemos que los materiales de investigación de calidad deben estar disponibles para laboratorios de todos los tamaños, no solo para instituciones bien financiadas.",
    "about.value3.title": "Innovación",
    "about.value3.desc": "Expandiendo continuamente nuestro catálogo y mejorando nuestros procesos para satisfacer las necesidades cambiantes de la comunidad de investigación.",
    "about.value4.title": "Transparencia",
    "about.value4.desc": "La comunicación abierta sobre nuestros métodos de prueba, abastecimiento y estándares de calidad genera confianza con nuestros clientes.",
    "about.teamTitle": "Liderazgo y Experiencia",
    "about.teamSubtitle": "Nuestro equipo combina décadas de experiencia en investigación farmacéutica, aseguramiento de calidad y logística global.",
    "about.certTitle": "Certificaciones de Calidad",
    "about.certSubtitle": "Nuestro compromiso con la calidad está respaldado por certificaciones reconocidas internacionalmente.",

    // Peptides
    "peptides.title": "Mundo de los Péptidos",
    "peptides.subtitle": "Péptidos Seleccionados y Contexto de Investigación",
    "peptides.searchPlaceholder": "Buscar compuestos...",
    "peptides.showing": "Mostrando",
    "peptides.of": "de",
    "peptides.compounds": "compuestos",
    "peptides.noResults": "No se encontraron compuestos que coincidan con su búsqueda.",
    "peptides.clearFilters": "Limpiar filtros",
    "peptides.reference": "Referencia:",
    "peptides.references": "Referencias:",
    "peptides.all": "Todos",

    // Calculator
    "calc.title": "PRC - Calculadora de Reconstitución de Péptidos",
    "calc.subtitle": "Calcule volúmenes precisos de reconstitución y dosificación para sus péptidos de investigación.",
    "calc.breadcrumbHome": "Inicio",
    "calc.selectPeptide": "Seleccionar Péptido",
    "calc.searchPeptide": "Buscar péptido...",
    "calc.vialSize": "Tamaño del Vial (mg)",
    "calc.bacWater": "Agua BAC (mL)",
    "calc.desiredDose": "Dosis Deseada (mcg)",
    "calc.calculate": "Calcular",
    "calc.reset": "Reiniciar",
    "calc.results": "Resultados",
    "calc.concentration": "Concentración",
    "calc.volumePerDose": "Volumen por Dosis",
    "calc.syringeUnits": "Unidades de Jeringa (U-100)",
    "calc.dosesPerVial": "Dosis por Vial",
    "calc.howItWorks": "Cómo Funciona",
    "calc.step1.title": "Seleccione su Péptido",
    "calc.step1.desc": "Elija de nuestra base de datos de más de 100 péptidos de investigación. Los tamaños de vial se completan automáticamente.",
    "calc.step2.title": "Configure el Volumen de Agua BAC",
    "calc.step2.desc": "Seleccione cuánta agua bacteriostática usará para la reconstitución.",
    "calc.step3.title": "Ingrese la Dosis Deseada",
    "calc.step3.desc": "Ingrese su dosis objetivo en microgramos (mcg) para cálculos precisos.",
    "calc.step4.title": "Obtenga sus Resultados",
    "calc.step4.desc": "Reciba concentración, volumen por dosis, unidades de jeringa y dosis por vial.",
    "calc.peptideVial": "Vial de Péptido",
    "calc.lyophilized": "Polvo liofilizado",
    "calc.u100Syringe": "Jeringa U-100",
    "calc.u100Desc": "1mL = 100 unidades",
    "calc.keyFormulas": "Fórmulas Clave",
    "calc.faqTitle": "Preguntas Frecuentes",
    "calc.disclaimer": "Esta calculadora es solo para referencia de investigación. Siempre verifique los cálculos de forma independiente. No para uso humano.",

    // Contact
    "contact.title": "Contáctenos",
    "contact.subtitle": "¿Tiene preguntas sobre nuestros productos o necesita asistencia? Estamos aquí para ayudar.",
    "contact.formTitle": "Envíenos un Mensaje",
    "contact.name": "Nombre Completo",
    "contact.email": "Correo Electrónico",
    "contact.subject": "Asunto",
    "contact.message": "Mensaje",
    "contact.send": "Enviar Mensaje",
    "contact.sending": "Enviando...",
    "contact.success": "¡Mensaje enviado con éxito!",
    "contact.error": "Error al enviar el mensaje. Inténtelo de nuevo.",
    "contact.infoTitle": "Póngase en Contacto",
    "contact.emailLabel": "Correo",
    "contact.locationLabel": "Ubicación",
    "contact.hoursLabel": "Horario de Atención",
    "contact.hoursValue": "Lunes - Viernes, 9:00 AM - 6:00 PM EST",
    "contact.responseLabel": "Tiempo de Respuesta",
    "contact.responseValue": "Dentro de 24 horas",

    // Footer
    "footer.description": "Salud Global. Verdaderas Soluciones. Transformando la investigación a través de soluciones de péptidos innovadoras y confiables.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.legal": "Legal",
    "footer.contactUs": "Contáctenos",
    "footer.terms": "Términos de Servicio",
    "footer.privacy": "Política de Privacidad",
    "footer.researchOnly": "Solo para Uso en Investigación",
    "footer.prc": "PRC - Calculadora de Reconstitución",
    "footer.rights": "Todos los derechos reservados.",
    "footer.termsShort": "Términos",
    "footer.privacyShort": "Privacidad",
    "footer.disclaimer": "AVISO LEGAL:",
    "footer.disclaimerText": "Estos productos no están aprobados por la Administración de Alimentos y Medicamentos de EE.UU. (FDA) para consumo humano o aplicaciones médicas. No deben usarse para ningún propósito que no sea la investigación científica. Las declaraciones presentadas en este sitio web no han sido evaluadas por la FDA.",
    "footer.labResearch": "Solo para uso en investigación de laboratorio.",
    "footer.notForHuman": "No para consumo humano o veterinario, ni administración.",

    // GMP Badges
    "badge.gmp": "Certificado GMP",
    "badge.iso": "Certificado ISO 9001",
    "badge.thirdParty": "Probado por Terceros",

    // Evidence Levels
    "evidence.all": "Todos los Niveles",
    "evidence.phaseIII": "Fase III / Aprobado",
    "evidence.phaseII": "Fase II",
    "evidence.clinical": "Clínico/Traslacional",
    "evidence.preclinical": "Preclínico",
    "evidence.mechanistic": "Mecanístico",

    // Terms
    "terms.title": "Términos de Servicio",
    "terms.lastUpdated": "Última Actualización",

    // Privacy
    "privacy.title": "Política de Privacidad",
    "privacy.lastUpdated": "Última Actualización",
  },

  pt: {
    // Nav
    "nav.home": "Início",
    "nav.about": "Sobre",
    "nav.peptides": "Mundo dos Peptídeos",
    "nav.contact": "Contato",
    "nav.prc": "PRC - Calculadora de Reconstituição",

    // Hero / Home
    "home.typewriter": "Peptídeos Testados em Laboratório a um Preço Acessível",
    "home.badge1": "Certificado ISO 9001",
    "home.badge2": "99%+ Satisfação",
    "home.badge3": "Distribuição Global",
    "home.headline": "Saúde Global.",
    "home.headline2": "Verdadeiras",
    "home.headline3": "Soluções.",
    "home.subheadline": "Fonte confiável de produtos de pesquisa de grau farmacêutico. Testados por terceiros, pré-misturados e prontos para uso em laboratório.",
    "home.exploreBtn": "Explorar Nossos Peptídeos",
    "home.contactBtn": "Fale Conosco",
    "home.statsTitle": "Confiança de Pesquisadores em Todo o Mundo",
    "home.statsSubtitle": "Nosso compromisso com qualidade e inovação conquistou a confiança de instituições de pesquisa globalmente.",
    "home.stat1.value": "99%+",
    "home.stat1.label": "Taxa de Pureza",
    "home.stat1.desc": "Verificado por laboratórios independentes de terceiros",
    "home.stat2.value": "50+",
    "home.stat2.label": "Países Atendidos",
    "home.stat2.desc": "Rede de distribuição global com envio confiável",
    "home.stat3.value": "500+",
    "home.stat3.label": "Produtos de Pesquisa",
    "home.stat3.desc": "Catálogo abrangente de peptídeos e compostos",
    "home.stat4.value": "24/7",
    "home.stat4.label": "Suporte Disponível",
    "home.stat4.desc": "Equipe dedicada para assistência técnica e de pedidos",
    "home.whyTitle": "Por Que Escolher a Tru & Co?",
    "home.whySubtitle": "Combinamos rigor científico com preços acessíveis para apoiar pesquisadores em todo o mundo.",
    "home.why1.title": "Pureza Testada em Laboratório",
    "home.why1.desc": "Cada lote passa por testes rigorosos de terceiros para garantir pureza de 99%+ para resultados de pesquisa confiáveis.",
    "home.why2.title": "Preços Acessíveis",
    "home.why2.desc": "Peptídeos de qualidade premium a preços competitivos, tornando a pesquisa avançada acessível para todos os laboratórios.",
    "home.why3.title": "Envio Global",
    "home.why3.desc": "Entrega mundial rápida e segura com manuseio adequado de cadeia fria para manter a integridade do produto.",
    "home.why4.title": "Suporte Especializado",
    "home.why4.desc": "Nossa equipe de especialistas fornece orientação técnica e atendimento ao cliente responsivo.",
    "home.why5.title": "Padrões GMP",
    "home.why5.desc": "Fabricado seguindo as diretrizes de Boas Práticas de Fabricação para qualidade consistente.",
    "home.why6.title": "Catálogo Extenso",
    "home.why6.desc": "Mais de 500 compostos de pesquisa incluindo peptídeos, proteínas e moléculas pequenas.",
    "home.ctaTitle": "Pronto para Avançar sua Pesquisa?",
    "home.ctaSubtitle": "Junte-se a milhares de pesquisadores em todo o mundo que confiam na Tru & Co para suas necessidades de peptídeos.",
    "home.ctaBtn": "Comece Hoje",
    "home.ctaContact": "Contate Nossa Equipe",

    // About
    "about.title": "Sobre a Tru & Co",
    "about.subtitle": "Pioneiros em soluções de pesquisa acessíveis com qualidade de grau farmacêutico.",
    "about.missionTitle": "Nossa Missão",
    "about.missionText": "Na Tru & Co, acreditamos que pesquisas inovadoras não devem ser limitadas por restrições orçamentárias. Nossa missão é fornecer à comunidade científica global peptídeos de grau farmacêutico testados em laboratório a preços que tornem a pesquisa avançada acessível para todos.",
    "about.visionTitle": "Nossa Visão",
    "about.visionText": "Tornar-se o fornecedor mais confiável do mundo de peptídeos de pesquisa, estabelecendo novos padrões de qualidade, acessibilidade e integridade científica na indústria de suprimentos de pesquisa.",
    "about.valuesTitle": "Nossos Valores Fundamentais",
    "about.value1.title": "Integridade Científica",
    "about.value1.desc": "Cada produto passa por testes rigorosos e controle de qualidade para garantir os mais altos padrões de pureza e confiabilidade.",
    "about.value2.title": "Acessibilidade",
    "about.value2.desc": "Acreditamos que materiais de pesquisa de qualidade devem estar disponíveis para laboratórios de todos os tamanhos, não apenas para instituições bem financiadas.",
    "about.value3.title": "Inovação",
    "about.value3.desc": "Expandindo continuamente nosso catálogo e melhorando nossos processos para atender às necessidades em evolução da comunidade de pesquisa.",
    "about.value4.title": "Transparência",
    "about.value4.desc": "Comunicação aberta sobre nossos métodos de teste, fornecimento e padrões de qualidade constrói confiança com nossos clientes.",
    "about.teamTitle": "Liderança e Expertise",
    "about.teamSubtitle": "Nossa equipe combina décadas de experiência em pesquisa farmacêutica, garantia de qualidade e logística global.",
    "about.certTitle": "Certificações de Qualidade",
    "about.certSubtitle": "Nosso compromisso com a qualidade é respaldado por certificações reconhecidas internacionalmente.",

    // Peptides
    "peptides.title": "Mundo dos Peptídeos",
    "peptides.subtitle": "Peptídeos Selecionados e Contexto de Pesquisa",
    "peptides.searchPlaceholder": "Buscar compostos...",
    "peptides.showing": "Mostrando",
    "peptides.of": "de",
    "peptides.compounds": "compostos",
    "peptides.noResults": "Nenhum composto encontrado para sua busca.",
    "peptides.clearFilters": "Limpar filtros",
    "peptides.reference": "Referência:",
    "peptides.references": "Referências:",
    "peptides.all": "Todos",

    // Calculator
    "calc.title": "PRC - Calculadora de Reconstituição de Peptídeos",
    "calc.subtitle": "Calcule volumes precisos de reconstituição e dosagem para seus peptídeos de pesquisa.",
    "calc.breadcrumbHome": "Início",
    "calc.selectPeptide": "Selecionar Peptídeo",
    "calc.searchPeptide": "Buscar peptídeo...",
    "calc.vialSize": "Tamanho do Frasco (mg)",
    "calc.bacWater": "Água BAC (mL)",
    "calc.desiredDose": "Dose Desejada (mcg)",
    "calc.calculate": "Calcular",
    "calc.reset": "Reiniciar",
    "calc.results": "Resultados",
    "calc.concentration": "Concentração",
    "calc.volumePerDose": "Volume por Dose",
    "calc.syringeUnits": "Unidades de Seringa (U-100)",
    "calc.dosesPerVial": "Doses por Frasco",
    "calc.howItWorks": "Como Funciona",
    "calc.step1.title": "Selecione seu Peptídeo",
    "calc.step1.desc": "Escolha em nosso banco de dados de mais de 100 peptídeos de pesquisa. Os tamanhos de frasco são preenchidos automaticamente.",
    "calc.step2.title": "Defina o Volume de Água BAC",
    "calc.step2.desc": "Selecione quanta água bacteriostática você usará para a reconstituição.",
    "calc.step3.title": "Insira a Dose Desejada",
    "calc.step3.desc": "Insira sua dose alvo em microgramas (mcg) para cálculos precisos.",
    "calc.step4.title": "Obtenha seus Resultados",
    "calc.step4.desc": "Receba concentração, volume por dose, unidades de seringa e doses por frasco.",
    "calc.peptideVial": "Frasco de Peptídeo",
    "calc.lyophilized": "Pó liofilizado",
    "calc.u100Syringe": "Seringa U-100",
    "calc.u100Desc": "1mL = 100 unidades",
    "calc.keyFormulas": "Fórmulas Principais",
    "calc.faqTitle": "Perguntas Frequentes",
    "calc.disclaimer": "Esta calculadora é apenas para referência de pesquisa. Sempre verifique os cálculos de forma independente. Não para uso humano.",

    // Contact
    "contact.title": "Fale Conosco",
    "contact.subtitle": "Tem perguntas sobre nossos produtos ou precisa de assistência? Estamos aqui para ajudar.",
    "contact.formTitle": "Envie-nos uma Mensagem",
    "contact.name": "Nome Completo",
    "contact.email": "Endereço de E-mail",
    "contact.subject": "Assunto",
    "contact.message": "Mensagem",
    "contact.send": "Enviar Mensagem",
    "contact.sending": "Enviando...",
    "contact.success": "Mensagem enviada com sucesso!",
    "contact.error": "Falha ao enviar mensagem. Tente novamente.",
    "contact.infoTitle": "Entre em Contato",
    "contact.emailLabel": "E-mail",
    "contact.locationLabel": "Localização",
    "contact.hoursLabel": "Horário de Atendimento",
    "contact.hoursValue": "Segunda - Sexta, 9:00 - 18:00 EST",
    "contact.responseLabel": "Tempo de Resposta",
    "contact.responseValue": "Em até 24 horas",

    // Footer
    "footer.description": "Saúde Global. Verdadeiras Soluções. Transformando a pesquisa através de soluções de peptídeos inovadoras e confiáveis.",
    "footer.quickLinks": "Links Rápidos",
    "footer.legal": "Legal",
    "footer.contactUs": "Contato",
    "footer.terms": "Termos de Serviço",
    "footer.privacy": "Política de Privacidade",
    "footer.researchOnly": "Apenas para Uso em Pesquisa",
    "footer.prc": "PRC - Calculadora de Reconstituição",
    "footer.rights": "Todos os direitos reservados.",
    "footer.termsShort": "Termos",
    "footer.privacyShort": "Privacidade",
    "footer.disclaimer": "AVISO LEGAL:",
    "footer.disclaimerText": "Estes produtos não são aprovados pela Administração de Alimentos e Medicamentos dos EUA (FDA) para consumo humano ou aplicações médicas. Não devem ser usados para qualquer finalidade que não seja pesquisa científica. As declarações apresentadas neste site não foram avaliadas pela FDA.",
    "footer.labResearch": "Apenas para uso em pesquisa laboratorial.",
    "footer.notForHuman": "Não para consumo humano ou veterinário, nem administração.",

    // GMP Badges
    "badge.gmp": "Certificado GMP",
    "badge.iso": "Certificado ISO 9001",
    "badge.thirdParty": "Testado por Terceiros",

    // Evidence Levels
    "evidence.all": "Todos os Níveis",
    "evidence.phaseIII": "Fase III / Aprovado",
    "evidence.phaseII": "Fase II",
    "evidence.clinical": "Clínico/Translacional",
    "evidence.preclinical": "Pré-clínico",
    "evidence.mechanistic": "Mecanístico",

    // Terms
    "terms.title": "Termos de Serviço",
    "terms.lastUpdated": "Última Atualização",

    // Privacy
    "privacy.title": "Política de Privacidade",
    "privacy.lastUpdated": "Última Atualização",
  },

  fr: {
    // Nav
    "nav.home": "Accueil",
    "nav.about": "À Propos",
    "nav.peptides": "Monde des Peptides",
    "nav.contact": "Contactez-nous",
    "nav.prc": "PRC - Calculateur de Reconstitution",

    // Hero / Home
    "home.typewriter": "Peptides Testés en Laboratoire à un Prix Abordable",
    "home.badge1": "Certifié ISO 9001",
    "home.badge2": "99%+ Satisfaction",
    "home.badge3": "Distribution Mondiale",
    "home.headline": "Santé Mondiale.",
    "home.headline2": "De Vraies",
    "home.headline3": "Solutions.",
    "home.subheadline": "Source fiable de produits de recherche de qualité pharmaceutique. Testés par des tiers, prémélangés et prêts pour une utilisation en laboratoire.",
    "home.exploreBtn": "Explorer Nos Peptides",
    "home.contactBtn": "Contactez-nous",
    "home.statsTitle": "La Confiance des Chercheurs du Monde Entier",
    "home.statsSubtitle": "Notre engagement envers la qualité et l'innovation a gagné la confiance des institutions de recherche à l'échelle mondiale.",
    "home.stat1.value": "99%+",
    "home.stat1.label": "Taux de Pureté",
    "home.stat1.desc": "Vérifié par des laboratoires tiers indépendants",
    "home.stat2.value": "50+",
    "home.stat2.label": "Pays Desservis",
    "home.stat2.desc": "Réseau de distribution mondial avec expédition fiable",
    "home.stat3.value": "500+",
    "home.stat3.label": "Produits de Recherche",
    "home.stat3.desc": "Catalogue complet de peptides et composés",
    "home.stat4.value": "24/7",
    "home.stat4.label": "Support Disponible",
    "home.stat4.desc": "Équipe dédiée pour l'assistance technique et les commandes",
    "home.whyTitle": "Pourquoi Choisir Tru & Co ?",
    "home.whySubtitle": "Nous combinons rigueur scientifique et prix accessibles pour soutenir les chercheurs du monde entier.",
    "home.why1.title": "Pureté Testée en Laboratoire",
    "home.why1.desc": "Chaque lot subit des tests rigoureux par des tiers pour garantir une pureté de 99%+ pour des résultats de recherche fiables.",
    "home.why2.title": "Prix Abordables",
    "home.why2.desc": "Peptides de qualité premium à des prix compétitifs, rendant la recherche avancée accessible à tous les laboratoires.",
    "home.why3.title": "Expédition Mondiale",
    "home.why3.desc": "Livraison mondiale rapide et sécurisée avec gestion appropriée de la chaîne du froid pour maintenir l'intégrité du produit.",
    "home.why4.title": "Support Expert",
    "home.why4.desc": "Notre équipe de spécialistes fournit des conseils techniques et un service client réactif.",
    "home.why5.title": "Normes BPF",
    "home.why5.desc": "Fabriqué selon les directives de Bonnes Pratiques de Fabrication pour une qualité constante.",
    "home.why6.title": "Catalogue Étendu",
    "home.why6.desc": "Plus de 500 composés de recherche incluant peptides, protéines et petites molécules.",
    "home.ctaTitle": "Prêt à Faire Avancer Votre Recherche ?",
    "home.ctaSubtitle": "Rejoignez des milliers de chercheurs dans le monde qui font confiance à Tru & Co pour leurs besoins en peptides.",
    "home.ctaBtn": "Commencez Aujourd'hui",
    "home.ctaContact": "Contactez Notre Équipe",

    // About
    "about.title": "À Propos de Tru & Co",
    "about.subtitle": "Pionniers des solutions de recherche accessibles avec une qualité de grade pharmaceutique.",
    "about.missionTitle": "Notre Mission",
    "about.missionText": "Chez Tru & Co, nous croyons que la recherche innovante ne devrait pas être limitée par des contraintes budgétaires. Notre mission est de fournir à la communauté scientifique mondiale des peptides de grade pharmaceutique testés en laboratoire à des prix qui rendent la recherche avancée accessible à tous.",
    "about.visionTitle": "Notre Vision",
    "about.visionText": "Devenir le fournisseur le plus fiable au monde de peptides de recherche, en établissant de nouvelles normes de qualité, d'accessibilité et d'intégrité scientifique dans l'industrie des fournitures de recherche.",
    "about.valuesTitle": "Nos Valeurs Fondamentales",
    "about.value1.title": "Intégrité Scientifique",
    "about.value1.desc": "Chaque produit subit des tests rigoureux et un contrôle qualité pour garantir les plus hauts standards de pureté et de fiabilité.",
    "about.value2.title": "Accessibilité",
    "about.value2.desc": "Nous croyons que les matériaux de recherche de qualité doivent être disponibles pour les laboratoires de toutes tailles, pas seulement pour les institutions bien financées.",
    "about.value3.title": "Innovation",
    "about.value3.desc": "Expansion continue de notre catalogue et amélioration de nos processus pour répondre aux besoins évolutifs de la communauté de recherche.",
    "about.value4.title": "Transparence",
    "about.value4.desc": "Une communication ouverte sur nos méthodes de test, notre approvisionnement et nos normes de qualité renforce la confiance avec nos clients.",
    "about.teamTitle": "Leadership et Expertise",
    "about.teamSubtitle": "Notre équipe combine des décennies d'expérience en recherche pharmaceutique, assurance qualité et logistique mondiale.",
    "about.certTitle": "Certifications de Qualité",
    "about.certSubtitle": "Notre engagement envers la qualité est soutenu par des certifications reconnues internationalement.",

    // Peptides
    "peptides.title": "Monde des Peptides",
    "peptides.subtitle": "Peptides Sélectionnés et Contexte de Recherche",
    "peptides.searchPlaceholder": "Rechercher des composés...",
    "peptides.showing": "Affichage de",
    "peptides.of": "sur",
    "peptides.compounds": "composés",
    "peptides.noResults": "Aucun composé trouvé correspondant à votre recherche.",
    "peptides.clearFilters": "Effacer les filtres",
    "peptides.reference": "Référence :",
    "peptides.references": "Références :",
    "peptides.all": "Tous",

    // Calculator
    "calc.title": "PRC - Calculateur de Reconstitution de Peptides",
    "calc.subtitle": "Calculez les volumes de reconstitution et le dosage précis pour vos peptides de recherche.",
    "calc.breadcrumbHome": "Accueil",
    "calc.selectPeptide": "Sélectionner un Peptide",
    "calc.searchPeptide": "Rechercher un peptide...",
    "calc.vialSize": "Taille du Flacon (mg)",
    "calc.bacWater": "Eau BAC (mL)",
    "calc.desiredDose": "Dose Souhaitée (mcg)",
    "calc.calculate": "Calculer",
    "calc.reset": "Réinitialiser",
    "calc.results": "Résultats",
    "calc.concentration": "Concentration",
    "calc.volumePerDose": "Volume par Dose",
    "calc.syringeUnits": "Unités de Seringue (U-100)",
    "calc.dosesPerVial": "Doses par Flacon",
    "calc.howItWorks": "Comment Ça Marche",
    "calc.step1.title": "Sélectionnez Votre Peptide",
    "calc.step1.desc": "Choisissez dans notre base de données de plus de 100 peptides de recherche. Les tailles de flacon se remplissent automatiquement.",
    "calc.step2.title": "Définissez le Volume d'Eau BAC",
    "calc.step2.desc": "Sélectionnez la quantité d'eau bactériostatique que vous utiliserez pour la reconstitution.",
    "calc.step3.title": "Entrez la Dose Souhaitée",
    "calc.step3.desc": "Saisissez votre dose cible en microgrammes (mcg) pour des calculs précis.",
    "calc.step4.title": "Obtenez Vos Résultats",
    "calc.step4.desc": "Recevez la concentration, le volume par dose, les unités de seringue et les doses par flacon.",
    "calc.peptideVial": "Flacon de Peptide",
    "calc.lyophilized": "Poudre lyophilisée",
    "calc.u100Syringe": "Seringue U-100",
    "calc.u100Desc": "1mL = 100 unités",
    "calc.keyFormulas": "Formules Clés",
    "calc.faqTitle": "Questions Fréquentes",
    "calc.disclaimer": "Ce calculateur est uniquement à titre de référence pour la recherche. Vérifiez toujours les calculs de manière indépendante. Pas pour usage humain.",

    // Contact
    "contact.title": "Contactez-nous",
    "contact.subtitle": "Vous avez des questions sur nos produits ou besoin d'assistance ? Nous sommes là pour vous aider.",
    "contact.formTitle": "Envoyez-nous un Message",
    "contact.name": "Nom Complet",
    "contact.email": "Adresse E-mail",
    "contact.subject": "Sujet",
    "contact.message": "Message",
    "contact.send": "Envoyer le Message",
    "contact.sending": "Envoi en cours...",
    "contact.success": "Message envoyé avec succès !",
    "contact.error": "Échec de l'envoi du message. Veuillez réessayer.",
    "contact.infoTitle": "Entrer en Contact",
    "contact.emailLabel": "E-mail",
    "contact.locationLabel": "Emplacement",
    "contact.hoursLabel": "Heures d'Ouverture",
    "contact.hoursValue": "Lundi - Vendredi, 9h00 - 18h00 EST",
    "contact.responseLabel": "Temps de Réponse",
    "contact.responseValue": "Sous 24 heures",

    // Footer
    "footer.description": "Santé Mondiale. De Vraies Solutions. Transformer la recherche grâce à des solutions peptidiques innovantes et fiables.",
    "footer.quickLinks": "Liens Rapides",
    "footer.legal": "Mentions Légales",
    "footer.contactUs": "Contactez-nous",
    "footer.terms": "Conditions d'Utilisation",
    "footer.privacy": "Politique de Confidentialité",
    "footer.researchOnly": "Uniquement pour la Recherche",
    "footer.prc": "PRC - Calculateur de Reconstitution",
    "footer.rights": "Tous droits réservés.",
    "footer.termsShort": "Conditions",
    "footer.privacyShort": "Confidentialité",
    "footer.disclaimer": "AVERTISSEMENT :",
    "footer.disclaimerText": "Ces produits ne sont pas approuvés par la Food and Drug Administration des États-Unis (FDA) pour la consommation humaine ou les applications médicales. Ils ne doivent être utilisés à aucune autre fin que la recherche scientifique. Les déclarations présentées sur ce site n'ont pas été évaluées par la FDA.",
    "footer.labResearch": "Uniquement pour la recherche en laboratoire.",
    "footer.notForHuman": "Pas pour la consommation humaine ou vétérinaire, ni l'administration.",

    // GMP Badges
    "badge.gmp": "Certifié BPF",
    "badge.iso": "Certifié ISO 9001",
    "badge.thirdParty": "Testé par des Tiers",

    // Evidence Levels
    "evidence.all": "Tous les Niveaux",
    "evidence.phaseIII": "Phase III / Approuvé",
    "evidence.phaseII": "Phase II",
    "evidence.clinical": "Clinique/Translationnel",
    "evidence.preclinical": "Préclinique",
    "evidence.mechanistic": "Mécanistique",

    // Terms
    "terms.title": "Conditions d'Utilisation",
    "terms.lastUpdated": "Dernière Mise à Jour",

    // Privacy
    "privacy.title": "Politique de Confidentialité",
    "privacy.lastUpdated": "Dernière Mise à Jour",
  },

  it: {
    // Nav
    "nav.home": "Home",
    "nav.about": "Chi Siamo",
    "nav.peptides": "Mondo dei Peptidi",
    "nav.contact": "Contattaci",
    "nav.prc": "PRC - Calcolatore di Ricostituzione",

    // Hero / Home
    "home.typewriter": "Peptidi Testati in Laboratorio a un Prezzo Accessibile",
    "home.badge1": "Certificato ISO 9001",
    "home.badge2": "99%+ Soddisfazione",
    "home.badge3": "Distribuzione Globale",
    "home.headline": "Salute Globale.",
    "home.headline2": "Vere",
    "home.headline3": "Soluzioni.",
    "home.subheadline": "Fonte affidabile di prodotti di ricerca di grado farmaceutico. Testati da terze parti, premiscelati e pronti per l'uso in laboratorio.",
    "home.exploreBtn": "Esplora i Nostri Peptidi",
    "home.contactBtn": "Contattaci",
    "home.statsTitle": "La Fiducia dei Ricercatori di Tutto il Mondo",
    "home.statsSubtitle": "Il nostro impegno per la qualità e l'innovazione ha guadagnato la fiducia delle istituzioni di ricerca a livello globale.",
    "home.stat1.value": "99%+",
    "home.stat1.label": "Tasso di Purezza",
    "home.stat1.desc": "Verificato da laboratori indipendenti di terze parti",
    "home.stat2.value": "50+",
    "home.stat2.label": "Paesi Serviti",
    "home.stat2.desc": "Rete di distribuzione globale con spedizione affidabile",
    "home.stat3.value": "500+",
    "home.stat3.label": "Prodotti di Ricerca",
    "home.stat3.desc": "Catalogo completo di peptidi e composti",
    "home.stat4.value": "24/7",
    "home.stat4.label": "Supporto Disponibile",
    "home.stat4.desc": "Team dedicato per assistenza tecnica e ordini",
    "home.whyTitle": "Perché Scegliere Tru & Co?",
    "home.whySubtitle": "Combiniamo rigore scientifico con prezzi accessibili per supportare i ricercatori di tutto il mondo.",
    "home.why1.title": "Purezza Testata in Laboratorio",
    "home.why1.desc": "Ogni lotto viene sottoposto a rigorosi test di terze parti per garantire una purezza del 99%+ per risultati di ricerca affidabili.",
    "home.why2.title": "Prezzi Accessibili",
    "home.why2.desc": "Peptidi di qualità premium a prezzi competitivi, rendendo la ricerca avanzata accessibile a tutti i laboratori.",
    "home.why3.title": "Spedizione Globale",
    "home.why3.desc": "Consegna mondiale rapida e sicura con gestione appropriata della catena del freddo per mantenere l'integrità del prodotto.",
    "home.why4.title": "Supporto Esperto",
    "home.why4.desc": "Il nostro team di specialisti fornisce guida tecnica e servizio clienti reattivo.",
    "home.why5.title": "Standard GMP",
    "home.why5.desc": "Prodotto seguendo le linee guida delle Buone Pratiche di Fabbricazione per una qualità costante.",
    "home.why6.title": "Catalogo Esteso",
    "home.why6.desc": "Oltre 500 composti di ricerca tra cui peptidi, proteine e piccole molecole.",
    "home.ctaTitle": "Pronto a Far Avanzare la Tua Ricerca?",
    "home.ctaSubtitle": "Unisciti a migliaia di ricercatori in tutto il mondo che si affidano a Tru & Co per le loro esigenze di peptidi.",
    "home.ctaBtn": "Inizia Oggi",
    "home.ctaContact": "Contatta il Nostro Team",

    // About
    "about.title": "Chi è Tru & Co",
    "about.subtitle": "Pionieri nelle soluzioni di ricerca accessibili con qualità di grado farmaceutico.",
    "about.missionTitle": "La Nostra Missione",
    "about.missionText": "In Tru & Co, crediamo che la ricerca innovativa non debba essere limitata da vincoli di budget. La nostra missione è fornire alla comunità scientifica globale peptidi di grado farmaceutico testati in laboratorio a prezzi che rendano la ricerca avanzata accessibile a tutti.",
    "about.visionTitle": "La Nostra Visione",
    "about.visionText": "Diventare il fornitore più affidabile al mondo di peptidi di ricerca, stabilendo nuovi standard di qualità, accessibilità e integrità scientifica nell'industria delle forniture di ricerca.",
    "about.valuesTitle": "I Nostri Valori Fondamentali",
    "about.value1.title": "Integrità Scientifica",
    "about.value1.desc": "Ogni prodotto viene sottoposto a test rigorosi e controllo qualità per garantire i più alti standard di purezza e affidabilità.",
    "about.value2.title": "Accessibilità",
    "about.value2.desc": "Crediamo che i materiali di ricerca di qualità debbano essere disponibili per laboratori di tutte le dimensioni, non solo per istituzioni ben finanziate.",
    "about.value3.title": "Innovazione",
    "about.value3.desc": "Espansione continua del nostro catalogo e miglioramento dei nostri processi per soddisfare le esigenze in evoluzione della comunità di ricerca.",
    "about.value4.title": "Trasparenza",
    "about.value4.desc": "La comunicazione aperta sui nostri metodi di test, approvvigionamento e standard di qualità costruisce fiducia con i nostri clienti.",
    "about.teamTitle": "Leadership ed Esperienza",
    "about.teamSubtitle": "Il nostro team combina decenni di esperienza nella ricerca farmaceutica, garanzia di qualità e logistica globale.",
    "about.certTitle": "Certificazioni di Qualità",
    "about.certSubtitle": "Il nostro impegno per la qualità è supportato da certificazioni riconosciute a livello internazionale.",

    // Peptides
    "peptides.title": "Mondo dei Peptidi",
    "peptides.subtitle": "Peptidi Selezionati e Contesto di Ricerca",
    "peptides.searchPlaceholder": "Cerca composti...",
    "peptides.showing": "Visualizzazione di",
    "peptides.of": "di",
    "peptides.compounds": "composti",
    "peptides.noResults": "Nessun composto trovato corrispondente alla tua ricerca.",
    "peptides.clearFilters": "Cancella filtri",
    "peptides.reference": "Riferimento:",
    "peptides.references": "Riferimenti:",
    "peptides.all": "Tutti",

    // Calculator
    "calc.title": "PRC - Calcolatore di Ricostituzione dei Peptidi",
    "calc.subtitle": "Calcola volumi precisi di ricostituzione e dosaggio per i tuoi peptidi di ricerca.",
    "calc.breadcrumbHome": "Home",
    "calc.selectPeptide": "Seleziona Peptide",
    "calc.searchPeptide": "Cerca peptide...",
    "calc.vialSize": "Dimensione Fiala (mg)",
    "calc.bacWater": "Acqua BAC (mL)",
    "calc.desiredDose": "Dose Desiderata (mcg)",
    "calc.calculate": "Calcola",
    "calc.reset": "Ripristina",
    "calc.results": "Risultati",
    "calc.concentration": "Concentrazione",
    "calc.volumePerDose": "Volume per Dose",
    "calc.syringeUnits": "Unità Siringa (U-100)",
    "calc.dosesPerVial": "Dosi per Fiala",
    "calc.howItWorks": "Come Funziona",
    "calc.step1.title": "Seleziona il Tuo Peptide",
    "calc.step1.desc": "Scegli dal nostro database di oltre 100 peptidi di ricerca. Le dimensioni delle fiale si compilano automaticamente.",
    "calc.step2.title": "Imposta il Volume di Acqua BAC",
    "calc.step2.desc": "Seleziona quanta acqua batteriostatica utilizzerai per la ricostituzione.",
    "calc.step3.title": "Inserisci la Dose Desiderata",
    "calc.step3.desc": "Inserisci la tua dose target in microgrammi (mcg) per calcoli precisi.",
    "calc.step4.title": "Ottieni i Tuoi Risultati",
    "calc.step4.desc": "Ricevi concentrazione, volume per dose, unità siringa e dosi per fiala.",
    "calc.peptideVial": "Fiala di Peptide",
    "calc.lyophilized": "Polvere liofilizzata",
    "calc.u100Syringe": "Siringa U-100",
    "calc.u100Desc": "1mL = 100 unità",
    "calc.keyFormulas": "Formule Chiave",
    "calc.faqTitle": "Domande Frequenti",
    "calc.disclaimer": "Questo calcolatore è solo a scopo di riferimento per la ricerca. Verificare sempre i calcoli in modo indipendente. Non per uso umano.",

    // Contact
    "contact.title": "Contattaci",
    "contact.subtitle": "Hai domande sui nostri prodotti o hai bisogno di assistenza? Siamo qui per aiutarti.",
    "contact.formTitle": "Inviaci un Messaggio",
    "contact.name": "Nome Completo",
    "contact.email": "Indirizzo E-mail",
    "contact.subject": "Oggetto",
    "contact.message": "Messaggio",
    "contact.send": "Invia Messaggio",
    "contact.sending": "Invio in corso...",
    "contact.success": "Messaggio inviato con successo!",
    "contact.error": "Invio del messaggio fallito. Riprova.",
    "contact.infoTitle": "Mettiti in Contatto",
    "contact.emailLabel": "E-mail",
    "contact.locationLabel": "Posizione",
    "contact.hoursLabel": "Orari di Apertura",
    "contact.hoursValue": "Lunedì - Venerdì, 9:00 - 18:00 EST",
    "contact.responseLabel": "Tempo di Risposta",
    "contact.responseValue": "Entro 24 ore",

    // Footer
    "footer.description": "Salute Globale. Vere Soluzioni. Trasformare la ricerca attraverso soluzioni peptidiche innovative e affidabili.",
    "footer.quickLinks": "Link Rapidi",
    "footer.legal": "Legale",
    "footer.contactUs": "Contattaci",
    "footer.terms": "Termini di Servizio",
    "footer.privacy": "Informativa sulla Privacy",
    "footer.researchOnly": "Solo per Uso di Ricerca",
    "footer.prc": "PRC - Calcolatore di Ricostituzione",
    "footer.rights": "Tutti i diritti riservati.",
    "footer.termsShort": "Termini",
    "footer.privacyShort": "Privacy",
    "footer.disclaimer": "AVVERTENZA:",
    "footer.disclaimerText": "Questi prodotti non sono approvati dalla Food and Drug Administration degli Stati Uniti (FDA) per il consumo umano o applicazioni mediche. Non devono essere utilizzati per scopi diversi dalla ricerca scientifica. Le dichiarazioni presentate su questo sito non sono state valutate dalla FDA.",
    "footer.labResearch": "Solo per uso nella ricerca di laboratorio.",
    "footer.notForHuman": "Non per consumo umano o veterinario, né somministrazione.",

    // GMP Badges
    "badge.gmp": "Certificato GMP",
    "badge.iso": "Certificato ISO 9001",
    "badge.thirdParty": "Testato da Terze Parti",

    // Evidence Levels
    "evidence.all": "Tutti i Livelli",
    "evidence.phaseIII": "Fase III / Approvato",
    "evidence.phaseII": "Fase II",
    "evidence.clinical": "Clinico/Traslazionale",
    "evidence.preclinical": "Preclinico",
    "evidence.mechanistic": "Meccanicistico",

    // Terms
    "terms.title": "Termini di Servizio",
    "terms.lastUpdated": "Ultimo Aggiornamento",

    // Privacy
    "privacy.title": "Informativa sulla Privacy",
    "privacy.lastUpdated": "Ultimo Aggiornamento",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("tru-co-language");
    return (saved as Language) || "en";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("tru-co-language", lang);
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language]?.[key] || translations.en[key] || key;
    },
    [language]
  );

  const currentLanguageInfo = languages.find((l) => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageInfo }}>
      {children}
    </LanguageContext.Provider>
  );
}
